// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/linkedin-promo/PromoAnimation.tsx": () => import("../components/mockups/linkedin-promo/PromoAnimation.tsx")
};
